### PR TITLE
OS-8556 bhyve uart is too fast

### PR DESCRIPTION
**Pull request by jperkin**
Details are in the ticket. I will do further testing of this, for now just looking for initial review.

### CODE REVIEW

**Review by danmcd — APPROVED** [review]
I have one, dumb, non-blocking question, and one not-so-dumb non-blocking request:

Question:  The interrupt you're now rate-limiting transmits one character? Or some number of characters?

Request:  Please file an illumos ticket for this also?  I expect non-Oxide folks who use C-bhyve will wanna have this.  Hell, maybe even upstream bhyve does?

**Comment by jperkin** [comment]
Yeh, this is the path that reads from the bhyve socket (that the metadata agent writes to) and writes the data into the UART. The interrupt fires once the FIFO (16 characters) is full, or earlier if there is no more data to read from the socket.

I'll definitely be filing an illumos ticket for this, but I'd like for it to soak for a while in SmartOS just in case there are any edge cases I missed.  Upstream bhyve won't be interested as the support for reading from a socket is only available on illumos.

**Comment by danmcd** [comment]
> Yeh, this is the path that reads from the bhyve socket (that the metadata agent writes to) and writes the data into the UART. The interrupt fires once the FIFO (16 characters) is full, or earlier if there is no more data to read from the socket.

Asking in the context of timing-setting.  I figure the delay should be a function of number-of-bytes-sent in the interrupt... maybe some hrtime_t statekeeping can help accumulate when to delay.

Thank you; I have one IA-blocker.  Have you tested real-world FreeBSD or NetBSD boots with this in place? Or is that testing still hard to do because mdata itself may need some rewhacks?

I'll IA this after I get an answer to that.  (After IA either you can push-and-squash, or I can. Lemme know either way.)

**Comment by jperkin** [comment]
> > Yeh, this is the path that reads from the bhyve socket (that the metadata agent writes to) and writes the data into the UART. The interrupt fires once the FIFO (16 characters) is full, or earlier if there is no more data to read from the socket.
> 
> Asking in the context of timing-setting. I figure the delay should be a function of number-of-bytes-sent in the interrupt... maybe some hrtime_t statekeeping can help accumulate when to delay.

Ah ok, so have a bursty transfer and then only have the pause once we've reached the number of bytes for the configured baud rate. Yeh, that could be interesting to explore.
 
> Thank you; I have one IA-blocker. Have you tested real-world FreeBSD or NetBSD boots with this in place? Or is that testing still hard to do because mdata itself may need some rewhacks?

Yes, both boot with this in place, notably with consoles attached via `vmadm console` so the UART code is being exercised there too.  Booting them with a patched bhyve confirms that both are now able to `mdata-get` arbitrary-sized keys.  mdata itself doesn't need any changes, this is enough to resolve the issue, at least in my testing, though as noted elsewhere I do have some proposed changes to mdata as part of this work.

**Comment by danmcd** [comment]
> > Thank you; I have one IA-blocker. Have you tested real-world FreeBSD or NetBSD boots with this in place? Or is that testing still hard to do because mdata itself may need some rewhacks?
> 
> Yes, both boot with this in place, notably with consoles attached via `vmadm console` so the UART code is being exercised there too. Booting them with a patched bhyve confirms that both are now able to `mdata-get` arbitrary-sized keys. mdata itself doesn't need any changes, this is enough to resolve the issue, at least in my testing, though as noted elsewhere I do have some proposed changes to mdata as part of this work.

Please make sure this paragraph's salient points are put into the ticket!

**Comment by jperkin** [comment]
Testing notes have been added to the ticket.

**Pull request merged**
