### PR TITLE
12455 want  SO_REUSEPORT support

### PR DESCRIPTION
**Pull request by cneira**
Hi,

Some applications require SO_REUSEPORT support  as this in some cases increases performance.
I checked at the work done here https://code.illumos.org/c/illumos-gate/+/464 and synced up the code to current illumos-joyent. 
I run the tests created for this feature and results are OK, I'm also running and unbound zone using reuseport options and so far so good.

Let me know which additional work is required to move this forward.

authored-by: araragihokuto@outlook.com
Co-authored-by: cneirabustos@gmail.com

Bests

### CODE REVIEW

**Comment by jclulow** [comment]
I think it would be best to take this into **illumos-gate** rather than just one downstream like **illumos-joyent**.

**Comment by danmcd** [comment]
Agreed @jclulow , especially for this one.  Best thing you can do IMHO, @cneira , is test the ever-living-daylights out of this wad, and report your findings!

**Comment by cneira** [comment]
@jclulow @danmcd  I'll try to find some time to build this using illumos-gate also I'll compile some pkgsrc packages to use SO_REUSEPORT to and exercise this change. 
I'm assuming I need to run a distribution using illumos-gate right?

**Comment by danmcd** [comment]
@cneira You can test this on SmartOS, but the ultimate fix should land in -gate first.  (I haven't seen if this affects code paths that are specific to SmartOS or not.)

**Comment by cneira** [comment]
@danmcd  @jclulow   I just uploaded changes for this for review https://code.illumos.org/c/illumos-gate/+/3457

**Pull request closed without merging**
