### PR TITLE
OS-8376 Alter LX's unlinkat() error code to match Linux kernel

### PR DESCRIPTION
**Pull request by smokris**
## Problem
- On a real Linux kernel, [attempting to remove a non-empty directory using `unlinkat()` fails with error `ENOTEMPTY`](https://github.com/torvalds/linux/blob/8157f4707360a17027538fa43b1b89b534c65eb9/fs/namei.c#L4053)
- On SmartOS LX, that scenario instead fails with `EEXIST`

This trips up `systemd-tmpfiles` since it [ignores `ENOENT` and `ENOTEMPTY`, but fails if another error is returned](https://github.com/systemd/systemd/blob/v239/src/tmpfiles/tmpfiles.c#L639).

This MR alters the error code to match Linux.

## Test
```c
#include <fcntl.h>
#include <unistd.h>
#include <stdio.h>
int main(void)
{
	int fd = open("/tmp", O_RDONLY);
	unlinkat(fd, "foo", AT_REMOVEDIR);
	perror(NULL);
	return 0;
}
```
### ✅ Result on a BHYVE zone
```console
# uname -a
Linux localhost 4.18.0-373.el8.x86_64 #1 SMP Tue Mar 22 15:11:47 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
# virt-what
bhyve
# mkdir /tmp/foo
# touch /tmp/foo/bar
# gcc test.c -o test
# ./test
Directory not empty
```
### ⚠️ Result on an LX zone before this MR
```console
# uname -a
Linux localhost 3.13.0 BrandZ virtual linux x86_64 x86_64 x86_64 GNU/Linux
# virt-what
lxc
# mkdir /tmp/foo
# touch /tmp/foo/bar
# gcc test.c -o test
# ./test
File exists
```
### ✅ Result on an LX zone with this MR
```console
# uname -a
Linux localhost 3.16.0 BrandZ virtual linux x86_64 x86_64 x86_64 GNU/Linux
# virt-what
lxc
# mkdir /tmp/foo
# touch /tmp/foo/bar
# gcc test.c -o test
# ./test
Directory not empty
```

### CODE REVIEW

**Comment by danmcd** [comment]
Good catch.  Bigger question is:  Should illumos in general do this too?  I wonder if your toy test program on other UNIX or UNIX-likes would also give you ENOTEMPTY?  If the answer is, "yes", it might be worth a followup for upstream illumos-gate.

Given how it appears ENOTEMPTY handling may have to occur in every filesystem type, this fix may be more appropriate for the short-term.  I'll review it properly no later than COB tomorrow.

**Comment by sjorge** [comment]
I wonder if this is related to my 9pfs issue I been having where if I do `rm -rf somedir/` on a 9p mount in a VM it failes with somedir/ exists.

**Comment by danmcd** [comment]
After further review, I might file an upstream illumos-gate bug about this, but that means I'm more likely to take this LX-only fix in sooner rather than later.

**Comment by danmcd** [comment]
BTW, rmdir() already does this in LX zones, Cf. https://github.com/TritonDataCenter/illumos-joyent/blob/master/usr/src/lib/brand/lx/lx_brand/common/file.c#L162

**Comment by danmcd** [comment]
The issue for more generic fixing of this is here:  https://www.illumos.org/issues/14631

**Comment by danmcd** [comment]
Because of our move to MNX, some things are in motion right now.  I plan on filing a proper OS ticket to go along with this, like I did for your SECCOMP contribution.  Pardon any latency.

**Review by danmcd — APPROVED** [review]
Marking as approved, but will not IA until we can file a proper OS bug, etc. etc.

**Comment by smokris** [comment]
@danmcd Thanks for reviewing and merging this, and for creating the upstream issue.

I've started gradually rolling PI 20220421T000508Z (the first to include this MR) into production, and will report back here if I notice any problems.

**Pull request merged**
