### PR TITLE
OS-8425 Bump net-early-admin Maximum MTU to 65535

### PR DESCRIPTION
**Pull request by noahmehl**
This PR is related to: https://github.com/TritonDataCenter/smartos-live/pull/860

Modern 10Gbe and above adapters and network gear support larger MTUs than 9000. This is important if users want to offer overlay networks of 9000 mtu, encapsulated in other protocols like vxlan, ipsec, vlan, etc.

This was merged for network.sh, but now net-early-admin has issues.

### CODE REVIEW

**Comment by danmcd** [comment]
We'll need to file an OS-ticket for this but otherwise this looks good, and you WILL get author credit one way or the other, @noahmehl .

**Comment by noahmehl** [comment]
Dan,

Thank you so much!

~Noah

**Comment by noahmehl** [comment]
BTW, I've only tested this by running the script itself on a running CN after making the change.  Seems to resolve my issue and not cause any other issues.  I've never built a PI for testing, so I would probably need some guidance there if that's required.

**Comment by danmcd** [comment]
I'm satisfied enough with your unit testing (i.e. the script itself).

**Comment by danmcd** [comment]
p.s. in the future, we prefer Full Name for the commiter.

`Author: noahmehl <noahmehl@gmail.com>`

Which is much better than some, but generally we prefer something like `Noah Mehl <noahmehl@gmail.com` e.g.

**Pull request merged**
