### PR TITLE
14892 pollhead lifetime too short in signalfd

### PR DESCRIPTION
**Pull request by danmcd**
Portions contributed by: Dan McDonald <danmcd@mnx.io>
Reviewed by: Dan McDonald <danmcd@mnx.io>
Reviewed by: Gordon Ross <gordon.w.ross@gmail.com>

(Early integration - also includes restored SmartOS brand hooks)

### CODE REVIEW

**Comment by danmcd** [comment]
NOTE:  Patrick's changes to -gate are here:  https://code.illumos.org/c/illumos-gate/+/2618

The ONLY differences between us and upstream are the brand hooks we (and OmniOS) have.

**Comment by danmcd** [comment]
See signalfd_consume_signal() in signalfd.c

**Review by travispaul — APPROVED** [review]

**Review by bahamat — APPROVED** [review]
Just rubber stamping, considering upstream has approved this and is only waiting on IA.

**Comment by danmcd** [comment]
Thank you.  We hammered this one pretty hard in testing, and $CUSTOMER seems happy with it too.

**Pull request merged**
