### PR TITLE
OS-8149 BHYVE: Fix MADT ACPI table generation

### PR DESCRIPTION
**Pull request by papertigers**
Contributed by: Andy Fiddaman <omnios@citrus-it.co.uk>

### CODE REVIEW

**Comment by sjorge** [comment]
@papertigers I think I saw an upstream diff for something similar? Is the same same one? Let me see if I can find it.

**Comment by papertigers** [comment]
This comes from https://github.com/omniosorg/illumos-omnios/commit/e22673e550

**Comment by sjorge** [comment]
It might be something different:
- https://reviews.freebsd.org/rS347124
- https://reviews.freebsd.org/rS346715

As both have to do with max cpu limit...

**Comment by danmcd** [comment]
@papertigers I know it's been a while, but was this obviated by upstream bhyve changes?

**Comment by danmcd** [comment]
> @papertigers I know it's been a while, but was this obviated by upstream bhyve changes?

Question also could be answered by @citrus-it or @sjorge

**Comment by danmcd** [comment]
Closing as superceded by upstream.

**Pull request closed without merging**
